// Generated by CoffeeScript 1.4.0
(function() {
  var HOST, PORT, net,
    _this = this;

  net = require("net");

  HOST = '127.0.0.1';

  PORT = 6969;

  net.createServer(function(sock) {
    sock.on('data', function(data) {
      return sock.write('world');
    });
    return sock.on('close', function() {});
  }).listen(PORT, HOST);

  console.log("Listening on " + HOST + " " + PORT);

}).call(this);
